services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: pierre
      POSTGRES_DB: pierre
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pierre"]
      interval: 5s
      retries: 5

  flask_app:
    build: .
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: flask_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  postgres_data:
    driver: local