name: My Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests_job:
    runs-on: ubuntu-latest
    steps:
      # Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installer Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # --- Cache pip ---
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Installer les dépendances
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Exécuter les tests
      - name: Run tests
        run: pytest -vv
