name: My Deploy
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: recupération du code avec une action checkoutv4
        uses: actions/checkout@v4
      - name: afficher le dossier d'exécution avec pwd
        run: pwd
      - name: Lister les fichiers et dossiers enfants avec ls-la
        run: ls -la
  pylint:
    needs: debug
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4
      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Restaurer le cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pylint et les requirements
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r app/requirements.txt
      - name: Lancer pylint
        run: |
          pylint app/app.py --fail-under=7
  unit-tests:
    needs: pylint
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code avec une GitHub action
        uses: actions/checkout@v4
      - name: Installer Python avec une action github
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Restaurer le cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Exécuter les tests unitaires
        run: pytest -vv tests_unitaires
  deploy_job:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy
        run: echo "Déploiement ici..."
  integration-tests:
    needs: deploy_job
    runs-on: ubuntu-latest
    steps:
      # - name: Récupération du code avec une GitHub action
      #   uses: actions/checkout@v4
      # - name: Installer Python avec une action github
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.12'
      # - name: Restaurer le cache pip
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      # - name: Installer les dépendances
        # run: |
          # python -m pip install --upgrade pip
          # pip install -r app/requirements.txt
      - name: Exécuter les tests d'intégration
        # run: pytest -vv /_integration_tests
        run: echo "test d'intégration ici..."